# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mw(object):
    def setupUi(self, mw):
        mw.setObjectName(_fromUtf8("mw"))
        mw.resize(796, 573)
        mw.setStyleSheet(_fromUtf8("background-color:#222222; color:#ffffff"))
        mw.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cw = QtGui.QWidget(mw)
        self.cw.setObjectName(_fromUtf8("cw"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.cw)
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.mainView = QtGui.QVBoxLayout()
        self.mainView.setMargin(11)
        self.mainView.setSpacing(6)
        self.mainView.setObjectName(_fromUtf8("mainView"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.startCalibr = QtGui.QToolButton(self.cw)
        self.startCalibr.setCheckable(True)
        self.startCalibr.setObjectName(_fromUtf8("startCalibr"))
        self.gridLayout_3.addWidget(self.startCalibr, 1, 1, 1, 1)
        self.startMeasurement = QtGui.QPushButton(self.cw)
        self.startMeasurement.setStyleSheet(_fromUtf8("background-color: rgb(99, 220, 85);\n"
"color: #222222;"))
        self.startMeasurement.setCheckable(True)
        self.startMeasurement.setObjectName(_fromUtf8("startMeasurement"))
        self.gridLayout_3.addWidget(self.startMeasurement, 1, 0, 1, 1)
        self.measurementDirCW = QtGui.QRadioButton(self.cw)
        self.measurementDirCW.setStyleSheet(_fromUtf8("border: 1px solid red;"))
        self.measurementDirCW.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("arrow-right"))
        self.measurementDirCW.setIcon(icon)
        self.measurementDirCW.setChecked(True)
        self.measurementDirCW.setObjectName(_fromUtf8("measurementDirCW"))
        self.gridLayout_3.addWidget(self.measurementDirCW, 1, 3, 1, 1)
        self.measurementDirCCW = QtGui.QRadioButton(self.cw)
        self.measurementDirCCW.setStyleSheet(_fromUtf8("border: 1px solid blue;"))
        self.measurementDirCCW.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("arrow-left"))
        self.measurementDirCCW.setIcon(icon)
        self.measurementDirCCW.setObjectName(_fromUtf8("measurementDirCCW"))
        self.gridLayout_3.addWidget(self.measurementDirCCW, 1, 2, 1, 1)
        self.plotPeriod = QtGui.QDoubleSpinBox(self.cw)
        self.plotPeriod.setMaximumSize(QtCore.QSize(100, 16777215))
        self.plotPeriod.setMinimum(1.0)
        self.plotPeriod.setMaximum(5000.0)
        self.plotPeriod.setProperty("value", 500.0)
        self.plotPeriod.setObjectName(_fromUtf8("plotPeriod"))
        self.gridLayout_3.addWidget(self.plotPeriod, 1, 5, 1, 1)
        self.measurementMode = QtGui.QComboBox(self.cw)
        self.measurementMode.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.measurementMode.setFont(font)
        self.measurementMode.setStyleSheet(_fromUtf8(""))
        self.measurementMode.setFrame(True)
        self.measurementMode.setObjectName(_fromUtf8("measurementMode"))
        self.measurementMode.addItem(_fromUtf8(""))
        self.measurementMode.addItem(_fromUtf8(""))
        self.measurementMode.addItem(_fromUtf8(""))
        self.measurementMode.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.measurementMode, 1, 4, 1, 1)
        self.saveToBtn = QtGui.QToolButton(self.cw)
        self.saveToBtn.setObjectName(_fromUtf8("saveToBtn"))
        self.gridLayout_3.addWidget(self.saveToBtn, 0, 0, 1, 1)
        self.saveToPath = QtGui.QLineEdit(self.cw)
        self.saveToPath.setObjectName(_fromUtf8("saveToPath"))
        self.gridLayout_3.addWidget(self.saveToPath, 0, 1, 1, 5)
        self.mainView.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leftView = QtGui.QVBoxLayout()
        self.leftView.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.leftView.setMargin(11)
        self.leftView.setSpacing(6)
        self.leftView.setObjectName(_fromUtf8("leftView"))
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.leftView.addItem(spacerItem)
        self.CCDPlot = QtGui.QVBoxLayout()
        self.CCDPlot.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.CCDPlot.setMargin(11)
        self.CCDPlot.setSpacing(6)
        self.CCDPlot.setObjectName(_fromUtf8("CCDPlot"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.CCDPlot.addItem(spacerItem1)
        self.leftView.addLayout(self.CCDPlot)
        self.dataPlot = QtGui.QVBoxLayout()
        self.dataPlot.setMargin(11)
        self.dataPlot.setSpacing(6)
        self.dataPlot.setObjectName(_fromUtf8("dataPlot"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.dataPlot.addItem(spacerItem2)
        self.leftView.addLayout(self.dataPlot)
        self.horizontalLayout.addLayout(self.leftView)
        self.rightView = QtGui.QVBoxLayout()
        self.rightView.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.rightView.setMargin(11)
        self.rightView.setSpacing(6)
        self.rightView.setObjectName(_fromUtf8("rightView"))
        self.dataSources = QtGui.QToolBox(self.cw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataSources.sizePolicy().hasHeightForWidth())
        self.dataSources.setSizePolicy(sizePolicy)
        self.dataSources.setMaximumSize(QtCore.QSize(400, 16777215))
        self.dataSources.setObjectName(_fromUtf8("dataSources"))
        self.page_HAMEG = QtGui.QWidget()
        self.page_HAMEG.setGeometry(QtCore.QRect(0, 0, 222, 315))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_HAMEG.sizePolicy().hasHeightForWidth())
        self.page_HAMEG.setSizePolicy(sizePolicy)
        self.page_HAMEG.setObjectName(_fromUtf8("page_HAMEG"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_HAMEG)
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.oscillo_config = QtGui.QGridLayout()
        self.oscillo_config.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.oscillo_config.setMargin(11)
        self.oscillo_config.setSpacing(6)
        self.oscillo_config.setObjectName(_fromUtf8("oscillo_config"))
        self.oscilloVdiv2 = QtGui.QComboBox(self.page_HAMEG)
        self.oscilloVdiv2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.oscilloVdiv2.setObjectName(_fromUtf8("oscilloVdiv2"))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscilloVdiv2.addItem(_fromUtf8(""))
        self.oscillo_config.addWidget(self.oscilloVdiv2, 3, 1, 1, 1)
        self.oscilloConnect = QtGui.QPushButton(self.page_HAMEG)
        self.oscilloConnect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.oscilloConnect.setCheckable(True)
        self.oscilloConnect.setObjectName(_fromUtf8("oscilloConnect"))
        self.oscillo_config.addWidget(self.oscilloConnect, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_HAMEG)
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setStyleSheet(_fromUtf8("color:cyan;"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.oscillo_config.addWidget(self.label_7, 2, 1, 1, 1)
        self.oscilloAutoSet = QtGui.QPushButton(self.page_HAMEG)
        self.oscilloAutoSet.setMaximumSize(QtCore.QSize(100, 16777215))
        self.oscilloAutoSet.setObjectName(_fromUtf8("oscilloAutoSet"))
        self.oscillo_config.addWidget(self.oscilloAutoSet, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.page_HAMEG)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setStyleSheet(_fromUtf8("color:orange;"))
        self.label.setObjectName(_fromUtf8("label"))
        self.oscillo_config.addWidget(self.label, 2, 0, 1, 1)
        self.oscilloYpos2 = QtGui.QSlider(self.page_HAMEG)
        self.oscilloYpos2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.oscilloYpos2.setOrientation(QtCore.Qt.Horizontal)
        self.oscilloYpos2.setObjectName(_fromUtf8("oscilloYpos2"))
        self.oscillo_config.addWidget(self.oscilloYpos2, 4, 1, 1, 1)
        self.oscilloVdiv1 = QtGui.QComboBox(self.page_HAMEG)
        self.oscilloVdiv1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.oscilloVdiv1.setObjectName(_fromUtf8("oscilloVdiv1"))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscilloVdiv1.addItem(_fromUtf8(""))
        self.oscillo_config.addWidget(self.oscilloVdiv1, 3, 0, 1, 1)
        self.oscilloYpos1 = QtGui.QSlider(self.page_HAMEG)
        self.oscilloYpos1.setMaximumSize(QtCore.QSize(100, 20))
        self.oscilloYpos1.setMaximum(30)
        self.oscilloYpos1.setOrientation(QtCore.Qt.Horizontal)
        self.oscilloYpos1.setObjectName(_fromUtf8("oscilloYpos1"))
        self.oscillo_config.addWidget(self.oscilloYpos1, 4, 0, 1, 1)
        self.oscilloSet = QtGui.QPushButton(self.page_HAMEG)
        self.oscilloSet.setMaximumSize(QtCore.QSize(100, 16777215))
        self.oscilloSet.setObjectName(_fromUtf8("oscilloSet"))
        self.oscillo_config.addWidget(self.oscilloSet, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_HAMEG)
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.oscillo_config.addWidget(self.label_9, 5, 0, 1, 1)
        self.oscilloTdiv = QtGui.QComboBox(self.page_HAMEG)
        self.oscilloTdiv.setMaximumSize(QtCore.QSize(100, 16777215))
        self.oscilloTdiv.setObjectName(_fromUtf8("oscilloTdiv"))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscilloTdiv.addItem(_fromUtf8(""))
        self.oscillo_config.addWidget(self.oscilloTdiv, 5, 1, 1, 1)
        self.oscilloAuto = QtGui.QCheckBox(self.page_HAMEG)
        self.oscilloAuto.setChecked(False)
        self.oscilloAuto.setObjectName(_fromUtf8("oscilloAuto"))
        self.oscillo_config.addWidget(self.oscilloAuto, 1, 1, 1, 1)
        self.CH1Val_std = QtGui.QLabel(self.page_HAMEG)
        self.CH1Val_std.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CH1Val_std.setObjectName(_fromUtf8("CH1Val_std"))
        self.oscillo_config.addWidget(self.CH1Val_std, 8, 0, 1, 1)
        self.oscilloFreq = QtGui.QLabel(self.page_HAMEG)
        self.oscilloFreq.setObjectName(_fromUtf8("oscilloFreq"))
        self.oscillo_config.addWidget(self.oscilloFreq, 9, 0, 1, 1)
        self.CH1Val = QtGui.QLabel(self.page_HAMEG)
        self.CH1Val.setStyleSheet(_fromUtf8("color:orange;"))
        self.CH1Val.setObjectName(_fromUtf8("CH1Val"))
        self.oscillo_config.addWidget(self.CH1Val, 6, 0, 1, 2)
        self.CH2Val = QtGui.QLabel(self.page_HAMEG)
        self.CH2Val.setStyleSheet(_fromUtf8("color:cyan;"))
        self.CH2Val.setObjectName(_fromUtf8("CH2Val"))
        self.oscillo_config.addWidget(self.CH2Val, 7, 0, 1, 2)
        self.oscilloRWShift = QtGui.QSpinBox(self.page_HAMEG)
        self.oscilloRWShift.setMaximum(8)
        self.oscilloRWShift.setSingleStep(1)
        self.oscilloRWShift.setProperty("value", 6)
        self.oscilloRWShift.setObjectName(_fromUtf8("oscilloRWShift"))
        self.oscillo_config.addWidget(self.oscilloRWShift, 8, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.oscillo_config)
        self.dataSources.addItem(self.page_HAMEG, _fromUtf8(""))
        self.page_CCD = QtGui.QWidget()
        self.page_CCD.setGeometry(QtCore.QRect(0, 0, 249, 121))
        self.page_CCD.setObjectName(_fromUtf8("page_CCD"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_CCD)
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.CCD_connect = QtGui.QPushButton(self.page_CCD)
        self.CCD_connect.setCheckable(True)
        self.CCD_connect.setObjectName(_fromUtf8("CCD_connect"))
        self.horizontalLayout_2.addWidget(self.CCD_connect)
        self.CCD_trigger = QtGui.QComboBox(self.page_CCD)
        self.CCD_trigger.setObjectName(_fromUtf8("CCD_trigger"))
        self.CCD_trigger.addItem(_fromUtf8(""))
        self.CCD_trigger.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.CCD_trigger)
        self.CCD_exposure = QtGui.QSpinBox(self.page_CCD)
        self.CCD_exposure.setMinimum(1)
        self.CCD_exposure.setMaximum(100)
        self.CCD_exposure.setProperty("value", 1)
        self.CCD_exposure.setObjectName(_fromUtf8("CCD_exposure"))
        self.horizontalLayout_2.addWidget(self.CCD_exposure)
        self.label_2 = QtGui.QLabel(self.page_CCD)
        self.label_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.page_CCD)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.D4Sigma = QtGui.QLabel(self.page_CCD)
        self.D4Sigma.setStyleSheet(_fromUtf8("font: 75 18pt \"Noto Sans\";\n"
"color: rgb(255, 0, 0);"))
        self.D4Sigma.setObjectName(_fromUtf8("D4Sigma"))
        self.horizontalLayout_3.addWidget(self.D4Sigma)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.page_CCD)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.CCD_sum = QtGui.QLabel(self.page_CCD)
        self.CCD_sum.setObjectName(_fromUtf8("CCD_sum"))
        self.horizontalLayout_4.addWidget(self.CCD_sum)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.dataSources.addItem(self.page_CCD, _fromUtf8(""))
        self.rightView.addWidget(self.dataSources)
        self.oscilloPlot = QtGui.QVBoxLayout()
        self.oscilloPlot.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.oscilloPlot.setMargin(11)
        self.oscilloPlot.setSpacing(0)
        self.oscilloPlot.setObjectName(_fromUtf8("oscilloPlot"))
        self.rightView.addLayout(self.oscilloPlot)
        self.horizontalLayout.addLayout(self.rightView)
        spacerItem3 = QtGui.QSpacerItem(0, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.mainView.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.mainView)
        self.toolBox = QtGui.QToolBox(self.cw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(320, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(410, 16777215))
        self.toolBox.setAcceptDrops(False)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.stepper_page = QtGui.QWidget()
        self.stepper_page.setGeometry(QtCore.QRect(0, 0, 320, 389))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper_page.sizePolicy().hasHeightForWidth())
        self.stepper_page.setSizePolicy(sizePolicy)
        self.stepper_page.setObjectName(_fromUtf8("stepper_page"))
        self.verticalLayout = QtGui.QVBoxLayout(self.stepper_page)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.setStepperSpeed = QtGui.QToolButton(self.stepper_page)
        self.setStepperSpeed.setObjectName(_fromUtf8("setStepperSpeed"))
        self.gridLayout_2.addWidget(self.setStepperSpeed, 3, 0, 1, 1)
        self.CWMoveToStop = QtGui.QToolButton(self.stepper_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CWMoveToStop.sizePolicy().hasHeightForWidth())
        self.CWMoveToStop.setSizePolicy(sizePolicy)
        self.CWMoveToStop.setMaximumSize(QtCore.QSize(50, 16777215))
        self.CWMoveToStop.setObjectName(_fromUtf8("CWMoveToStop"))
        self.gridLayout_2.addWidget(self.CWMoveToStop, 4, 0, 1, 1)
        self.openAngleSensorPort = QtGui.QToolButton(self.stepper_page)
        self.openAngleSensorPort.setCheckable(True)
        self.openAngleSensorPort.setObjectName(_fromUtf8("openAngleSensorPort"))
        self.gridLayout_2.addWidget(self.openAngleSensorPort, 0, 0, 1, 1)
        self.currentAngle = QtGui.QLabel(self.stepper_page)
        self.currentAngle.setStyleSheet(_fromUtf8("color:yellow; font-size:40pt;"))
        self.currentAngle.setObjectName(_fromUtf8("currentAngle"))
        self.gridLayout_2.addWidget(self.currentAngle, 4, 1, 2, 4)
        self.angleSensorPort = QtGui.QSpinBox(self.stepper_page)
        self.angleSensorPort.setMaximumSize(QtCore.QSize(50, 16777215))
        self.angleSensorPort.setObjectName(_fromUtf8("angleSensorPort"))
        self.gridLayout_2.addWidget(self.angleSensorPort, 0, 1, 1, 1)
        self.stepperSpeed = QtGui.QSlider(self.stepper_page)
        self.stepperSpeed.setMaximumSize(QtCore.QSize(200, 16777215))
        self.stepperSpeed.setMinimum(50)
        self.stepperSpeed.setMaximum(2100)
        self.stepperSpeed.setProperty("value", 512)
        self.stepperSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.stepperSpeed.setObjectName(_fromUtf8("stepperSpeed"))
        self.gridLayout_2.addWidget(self.stepperSpeed, 1, 0, 2, 5)
        self.stepperSpeedValue = QtGui.QSpinBox(self.stepper_page)
        self.stepperSpeedValue.setMinimum(1)
        self.stepperSpeedValue.setMaximum(3000)
        self.stepperSpeedValue.setObjectName(_fromUtf8("stepperSpeedValue"))
        self.gridLayout_2.addWidget(self.stepperSpeedValue, 1, 5, 2, 1)
        self.CWHome = QtGui.QToolButton(self.stepper_page)
        self.CWHome.setMaximumSize(QtCore.QSize(50, 16777215))
        self.CWHome.setObjectName(_fromUtf8("CWHome"))
        self.gridLayout_2.addWidget(self.CWHome, 5, 0, 1, 1)
        self.CCWMoveToStop = QtGui.QToolButton(self.stepper_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CCWMoveToStop.sizePolicy().hasHeightForWidth())
        self.CCWMoveToStop.setSizePolicy(sizePolicy)
        self.CCWMoveToStop.setMaximumSize(QtCore.QSize(50, 16777215))
        self.CCWMoveToStop.setObjectName(_fromUtf8("CCWMoveToStop"))
        self.gridLayout_2.addWidget(self.CCWMoveToStop, 4, 5, 1, 1)
        self.CCWHome = QtGui.QToolButton(self.stepper_page)
        self.CCWHome.setMaximumSize(QtCore.QSize(50, 16777215))
        self.CCWHome.setObjectName(_fromUtf8("CCWHome"))
        self.gridLayout_2.addWidget(self.CCWHome, 5, 5, 1, 1)
        self.stepperStop = QtGui.QToolButton(self.stepper_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepperStop.sizePolicy().hasHeightForWidth())
        self.stepperStop.setSizePolicy(sizePolicy)
        self.stepperStop.setMaximumSize(QtCore.QSize(100, 50))
        self.stepperStop.setStyleSheet(_fromUtf8("border: 1px solid red;"))
        self.stepperStop.setObjectName(_fromUtf8("stepperStop"))
        self.gridLayout_2.addWidget(self.stepperStop, 0, 5, 1, 1)
        self.stepperLock = QtGui.QToolButton(self.stepper_page)
        self.stepperLock.setCheckable(True)
        self.stepperLock.setChecked(True)
        self.stepperLock.setObjectName(_fromUtf8("stepperLock"))
        self.gridLayout_2.addWidget(self.stepperLock, 0, 2, 1, 3)
        self.setCustomAngle = QtGui.QToolButton(self.stepper_page)
        self.setCustomAngle.setMaximumSize(QtCore.QSize(100, 16777215))
        self.setCustomAngle.setObjectName(_fromUtf8("setCustomAngle"))
        self.gridLayout_2.addWidget(self.setCustomAngle, 3, 5, 1, 1)
        self.moveToAngle = QtGui.QToolButton(self.stepper_page)
        self.moveToAngle.setObjectName(_fromUtf8("moveToAngle"))
        self.gridLayout_2.addWidget(self.moveToAngle, 3, 1, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.toolBox.addItem(self.stepper_page, _fromUtf8(""))
        self.Settings = QtGui.QWidget()
        self.Settings.setGeometry(QtCore.QRect(0, 0, 326, 376))
        self.Settings.setObjectName(_fromUtf8("Settings"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Settings)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setMargin(11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setMargin(11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.prevFilter = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevFilter.sizePolicy().hasHeightForWidth())
        self.prevFilter.setSizePolicy(sizePolicy)
        self.prevFilter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.prevFilter.setObjectName(_fromUtf8("prevFilter"))
        self.gridLayout_8.addWidget(self.prevFilter, 0, 0, 1, 1)
        self.nextFilter = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextFilter.sizePolicy().hasHeightForWidth())
        self.nextFilter.setSizePolicy(sizePolicy)
        self.nextFilter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.nextFilter.setObjectName(_fromUtf8("nextFilter"))
        self.gridLayout_8.addWidget(self.nextFilter, 0, 1, 1, 1)
        self.filtersTab = QtGui.QTableWidget(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtersTab.sizePolicy().hasHeightForWidth())
        self.filtersTab.setSizePolicy(sizePolicy)
        self.filtersTab.setRowCount(6)
        self.filtersTab.setColumnCount(3)
        self.filtersTab.setObjectName(_fromUtf8("filtersTab"))
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.filtersTab.setItem(5, 2, item)
        self.gridLayout_8.addWidget(self.filtersTab, 1, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.globalConfig = QtGui.QTableWidget(self.groupBox)
        self.globalConfig.setObjectName(_fromUtf8("globalConfig"))
        self.globalConfig.setColumnCount(2)
        self.globalConfig.setRowCount(23)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setVerticalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.globalConfig.setItem(3, 1, item)
        self.verticalLayout_3.addWidget(self.globalConfig)
        self.saveConfig = QtGui.QPushButton(self.groupBox)
        self.saveConfig.setObjectName(_fromUtf8("saveConfig"))
        self.verticalLayout_3.addWidget(self.saveConfig)
        self.gridLayout_7.addWidget(self.groupBox, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.toolBox.addItem(self.Settings, _fromUtf8(""))
        self.SMD = QtGui.QWidget()
        self.SMD.setGeometry(QtCore.QRect(0, -180, 307, 569))
        self.SMD.setObjectName(_fromUtf8("SMD"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.SMD)
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.SMD_connect = QtGui.QToolButton(self.SMD)
        self.SMD_connect.setCheckable(True)
        self.SMD_connect.setObjectName(_fromUtf8("SMD_connect"))
        self.verticalLayout_4.addWidget(self.SMD_connect)
        self.groupBox_2 = QtGui.QGroupBox(self.SMD)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setContentsMargins(0, 9, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.SM1_rightEndstop = QtGui.QCheckBox(self.groupBox_2)
        self.SM1_rightEndstop.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_rightEndstop.setText(_fromUtf8(""))
        self.SM1_rightEndstop.setObjectName(_fromUtf8("SM1_rightEndstop"))
        self.gridLayout.addWidget(self.SM1_rightEndstop, 7, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.SM1_leftEndstop = QtGui.QCheckBox(self.groupBox_2)
        self.SM1_leftEndstop.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_leftEndstop.setText(_fromUtf8(""))
        self.SM1_leftEndstop.setCheckable(True)
        self.SM1_leftEndstop.setChecked(False)
        self.SM1_leftEndstop.setAutoRepeat(False)
        self.SM1_leftEndstop.setObjectName(_fromUtf8("SM1_leftEndstop"))
        self.gridLayout.addWidget(self.SM1_leftEndstop, 7, 1, 1, 1)
        self.SM1_speed_val = QtGui.QSpinBox(self.groupBox_2)
        self.SM1_speed_val.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_speed_val.setMinimum(1)
        self.SM1_speed_val.setMaximum(90000)
        self.SM1_speed_val.setProperty("value", 160)
        self.SM1_speed_val.setObjectName(_fromUtf8("SM1_speed_val"))
        self.gridLayout.addWidget(self.SM1_speed_val, 6, 1, 1, 1)
        self.SM1_stepsCounter = QtGui.QLabel(self.groupBox_2)
        self.SM1_stepsCounter.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_stepsCounter.setObjectName(_fromUtf8("SM1_stepsCounter"))
        self.gridLayout.addWidget(self.SM1_stepsCounter, 6, 2, 1, 1)
        self.SM1_speed = QtGui.QSlider(self.groupBox_2)
        self.SM1_speed.setMinimum(1)
        self.SM1_speed.setMaximum(255)
        self.SM1_speed.setPageStep(20)
        self.SM1_speed.setProperty("value", 160)
        self.SM1_speed.setOrientation(QtCore.Qt.Horizontal)
        self.SM1_speed.setObjectName(_fromUtf8("SM1_speed"))
        self.gridLayout.addWidget(self.SM1_speed, 5, 1, 1, 2)
        self.SM1_position = QtGui.QLabel(self.groupBox_2)
        self.SM1_position.setMinimumSize(QtCore.QSize(0, 50))
        self.SM1_position.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.SM1_position.setFont(font)
        self.SM1_position.setObjectName(_fromUtf8("SM1_position"))
        self.gridLayout.addWidget(self.SM1_position, 3, 0, 1, 3)
        self.SM1_step = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.SM1_step.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_step.setDecimals(6)
        self.SM1_step.setMinimum(1e-06)
        self.SM1_step.setMaximum(99999999999.0)
        self.SM1_step.setProperty("value", 10.0)
        self.SM1_step.setObjectName(_fromUtf8("SM1_step"))
        self.gridLayout.addWidget(self.SM1_step, 0, 0, 1, 2)
        self.SM1_moving = QtGui.QRadioButton(self.groupBox_2)
        self.SM1_moving.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_moving.setText(_fromUtf8(""))
        self.SM1_moving.setObjectName(_fromUtf8("SM1_moving"))
        self.gridLayout.addWidget(self.SM1_moving, 0, 2, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.SM1_left2end = QtGui.QToolButton(self.groupBox_2)
        self.SM1_left2end.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_left2end.setObjectName(_fromUtf8("SM1_left2end"))
        self.horizontalLayout_6.addWidget(self.SM1_left2end)
        self.SM1_stepLeft = QtGui.QPushButton(self.groupBox_2)
        self.SM1_stepLeft.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_stepLeft.setObjectName(_fromUtf8("SM1_stepLeft"))
        self.horizontalLayout_6.addWidget(self.SM1_stepLeft)
        self.SM1_stepRight = QtGui.QPushButton(self.groupBox_2)
        self.SM1_stepRight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_stepRight.setObjectName(_fromUtf8("SM1_stepRight"))
        self.horizontalLayout_6.addWidget(self.SM1_stepRight)
        self.SM1_right2end = QtGui.QToolButton(self.groupBox_2)
        self.SM1_right2end.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_right2end.setObjectName(_fromUtf8("SM1_right2end"))
        self.horizontalLayout_6.addWidget(self.SM1_right2end)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 3)
        self.SM1_tabStep = QtGui.QCheckBox(self.groupBox_2)
        self.SM1_tabStep.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_tabStep.setObjectName(_fromUtf8("SM1_tabStep"))
        self.gridLayout.addWidget(self.SM1_tabStep, 6, 0, 1, 1)
        self.SM1_reset = QtGui.QPushButton(self.groupBox_2)
        self.SM1_reset.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_reset.setObjectName(_fromUtf8("SM1_reset"))
        self.gridLayout.addWidget(self.SM1_reset, 4, 0, 1, 1)
        self.SM1_stop = QtGui.QPushButton(self.groupBox_2)
        self.SM1_stop.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_stop.setObjectName(_fromUtf8("SM1_stop"))
        self.gridLayout.addWidget(self.SM1_stop, 5, 0, 1, 1)
        self.SM1_absMove = QtGui.QPushButton(self.groupBox_2)
        self.SM1_absMove.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_absMove.setObjectName(_fromUtf8("SM1_absMove"))
        self.gridLayout.addWidget(self.SM1_absMove, 4, 1, 1, 1)
        self.SM1_lock = QtGui.QPushButton(self.groupBox_2)
        self.SM1_lock.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM1_lock.setCheckable(True)
        self.SM1_lock.setChecked(True)
        self.SM1_lock.setObjectName(_fromUtf8("SM1_lock"))
        self.gridLayout.addWidget(self.SM1_lock, 4, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.SMD)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setContentsMargins(0, 11, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_5.setMargin(11)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 8, 0, 1, 1)
        self.SM2_speed_val = QtGui.QSpinBox(self.groupBox_3)
        self.SM2_speed_val.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_speed_val.setMinimum(1)
        self.SM2_speed_val.setMaximum(90000)
        self.SM2_speed_val.setProperty("value", 80)
        self.SM2_speed_val.setObjectName(_fromUtf8("SM2_speed_val"))
        self.gridLayout_5.addWidget(self.SM2_speed_val, 6, 1, 1, 1)
        self.SM2_rightEndstop = QtGui.QCheckBox(self.groupBox_3)
        self.SM2_rightEndstop.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_rightEndstop.setText(_fromUtf8(""))
        self.SM2_rightEndstop.setObjectName(_fromUtf8("SM2_rightEndstop"))
        self.gridLayout_5.addWidget(self.SM2_rightEndstop, 8, 1, 1, 1)
        self.SM2_leftEndstop = QtGui.QCheckBox(self.groupBox_3)
        self.SM2_leftEndstop.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_leftEndstop.setText(_fromUtf8(""))
        self.SM2_leftEndstop.setCheckable(True)
        self.SM2_leftEndstop.setChecked(False)
        self.SM2_leftEndstop.setAutoRepeat(False)
        self.SM2_leftEndstop.setObjectName(_fromUtf8("SM2_leftEndstop"))
        self.gridLayout_5.addWidget(self.SM2_leftEndstop, 8, 2, 1, 1)
        self.SM2_lock = QtGui.QPushButton(self.groupBox_3)
        self.SM2_lock.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_lock.setCheckable(True)
        self.SM2_lock.setChecked(True)
        self.SM2_lock.setObjectName(_fromUtf8("SM2_lock"))
        self.gridLayout_5.addWidget(self.SM2_lock, 4, 2, 1, 1)
        self.SM2_speed = QtGui.QSlider(self.groupBox_3)
        self.SM2_speed.setMinimum(1)
        self.SM2_speed.setMaximum(255)
        self.SM2_speed.setPageStep(20)
        self.SM2_speed.setProperty("value", 80)
        self.SM2_speed.setSliderPosition(80)
        self.SM2_speed.setOrientation(QtCore.Qt.Horizontal)
        self.SM2_speed.setObjectName(_fromUtf8("SM2_speed"))
        self.gridLayout_5.addWidget(self.SM2_speed, 5, 1, 1, 2)
        self.SM2_stepsCounter = QtGui.QLabel(self.groupBox_3)
        self.SM2_stepsCounter.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_stepsCounter.setObjectName(_fromUtf8("SM2_stepsCounter"))
        self.gridLayout_5.addWidget(self.SM2_stepsCounter, 6, 2, 1, 1)
        self.SM2_position = QtGui.QLabel(self.groupBox_3)
        self.SM2_position.setMinimumSize(QtCore.QSize(0, 50))
        self.SM2_position.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.SM2_position.setFont(font)
        self.SM2_position.setObjectName(_fromUtf8("SM2_position"))
        self.gridLayout_5.addWidget(self.SM2_position, 3, 0, 1, 3)
        self.SM2_step = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.SM2_step.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_step.setDecimals(6)
        self.SM2_step.setMinimum(1e-06)
        self.SM2_step.setMaximum(99999999999.0)
        self.SM2_step.setProperty("value", 10.0)
        self.SM2_step.setObjectName(_fromUtf8("SM2_step"))
        self.gridLayout_5.addWidget(self.SM2_step, 0, 0, 1, 2)
        self.SM2_moving = QtGui.QRadioButton(self.groupBox_3)
        self.SM2_moving.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_moving.setText(_fromUtf8(""))
        self.SM2_moving.setObjectName(_fromUtf8("SM2_moving"))
        self.gridLayout_5.addWidget(self.SM2_moving, 0, 2, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.SM2_left2end = QtGui.QToolButton(self.groupBox_3)
        self.SM2_left2end.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_left2end.setObjectName(_fromUtf8("SM2_left2end"))
        self.horizontalLayout_7.addWidget(self.SM2_left2end)
        self.SM2_stepLeft = QtGui.QPushButton(self.groupBox_3)
        self.SM2_stepLeft.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_stepLeft.setObjectName(_fromUtf8("SM2_stepLeft"))
        self.horizontalLayout_7.addWidget(self.SM2_stepLeft)
        self.SM2_stepRight = QtGui.QPushButton(self.groupBox_3)
        self.SM2_stepRight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_stepRight.setObjectName(_fromUtf8("SM2_stepRight"))
        self.horizontalLayout_7.addWidget(self.SM2_stepRight)
        self.SM2_right2end = QtGui.QToolButton(self.groupBox_3)
        self.SM2_right2end.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_right2end.setObjectName(_fromUtf8("SM2_right2end"))
        self.horizontalLayout_7.addWidget(self.SM2_right2end)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 1, 0, 1, 3)
        self.SM2_tabStep = QtGui.QCheckBox(self.groupBox_3)
        self.SM2_tabStep.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_tabStep.setObjectName(_fromUtf8("SM2_tabStep"))
        self.gridLayout_5.addWidget(self.SM2_tabStep, 6, 0, 1, 1)
        self.SM2_reset = QtGui.QPushButton(self.groupBox_3)
        self.SM2_reset.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_reset.setObjectName(_fromUtf8("SM2_reset"))
        self.gridLayout_5.addWidget(self.SM2_reset, 4, 0, 1, 1)
        self.SM2_absMove = QtGui.QPushButton(self.groupBox_3)
        self.SM2_absMove.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_absMove.setObjectName(_fromUtf8("SM2_absMove"))
        self.gridLayout_5.addWidget(self.SM2_absMove, 4, 1, 1, 1)
        self.SM2_stop = QtGui.QPushButton(self.groupBox_3)
        self.SM2_stop.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SM2_stop.setObjectName(_fromUtf8("SM2_stop"))
        self.gridLayout_5.addWidget(self.SM2_stop, 5, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.toolBox.addItem(self.SMD, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.toolBox)
        mw.setCentralWidget(self.cw)
        self.menuBar = QtGui.QMenuBar(mw)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 796, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFIle = QtGui.QMenu(self.menuBar)
        self.menuFIle.setObjectName(_fromUtf8("menuFIle"))
        self.menuPlot = QtGui.QMenu(self.menuBar)
        self.menuPlot.setObjectName(_fromUtf8("menuPlot"))
        mw.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(mw)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        mw.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(mw)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        mw.setStatusBar(self.statusBar)
        self.actionClose = QtGui.QAction(mw)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionClean = QtGui.QAction(mw)
        self.actionClean.setObjectName(_fromUtf8("actionClean"))
        self.menuFIle.addAction(self.actionClose)
        self.menuPlot.addAction(self.actionClean)
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuPlot.menuAction())

        self.retranslateUi(mw)
        self.measurementMode.setCurrentIndex(1)
        self.dataSources.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mw)

    def retranslateUi(self, mw):
        mw.setWindowTitle(_translate("mw", "MainWindow", None))
        self.startCalibr.setText(_translate("mw", "Calibr", None))
        self.startMeasurement.setText(_translate("mw", "Start", None))
        self.measurementMode.setItemText(0, _translate("mw", "SM1_EndStop", None))
        self.measurementMode.setItemText(1, _translate("mw", "SM1_step", None))
        self.measurementMode.setItemText(2, _translate("mw", "SM2_EndStop", None))
        self.measurementMode.setItemText(3, _translate("mw", "SM2_step", None))
        self.saveToBtn.setText(_translate("mw", "File ...", None))
        self.saveToPath.setText(_translate("mw", "./test.txt", None))
        self.oscilloVdiv2.setItemText(0, _translate("mw", "1mV", None))
        self.oscilloVdiv2.setItemText(1, _translate("mw", "2mV", None))
        self.oscilloVdiv2.setItemText(2, _translate("mw", "5mV", None))
        self.oscilloVdiv2.setItemText(3, _translate("mw", "10mV", None))
        self.oscilloVdiv2.setItemText(4, _translate("mw", "20mV", None))
        self.oscilloVdiv2.setItemText(5, _translate("mw", "50mV", None))
        self.oscilloVdiv2.setItemText(6, _translate("mw", "100mV", None))
        self.oscilloVdiv2.setItemText(7, _translate("mw", "200mV", None))
        self.oscilloVdiv2.setItemText(8, _translate("mw", "500mV", None))
        self.oscilloVdiv2.setItemText(9, _translate("mw", "1V", None))
        self.oscilloVdiv2.setItemText(10, _translate("mw", "2V", None))
        self.oscilloVdiv2.setItemText(11, _translate("mw", "5V", None))
        self.oscilloVdiv2.setItemText(12, _translate("mw", "10V", None))
        self.oscilloVdiv2.setItemText(13, _translate("mw", "20V", None))
        self.oscilloConnect.setText(_translate("mw", "Connect", None))
        self.label_7.setText(_translate("mw", "CH2", None))
        self.oscilloAutoSet.setText(_translate("mw", "Autoset", None))
        self.label.setText(_translate("mw", "CH1:", None))
        self.oscilloVdiv1.setItemText(0, _translate("mw", "1mV", None))
        self.oscilloVdiv1.setItemText(1, _translate("mw", "2mV", None))
        self.oscilloVdiv1.setItemText(2, _translate("mw", "5mV", None))
        self.oscilloVdiv1.setItemText(3, _translate("mw", "10mV", None))
        self.oscilloVdiv1.setItemText(4, _translate("mw", "20mV", None))
        self.oscilloVdiv1.setItemText(5, _translate("mw", "50mV", None))
        self.oscilloVdiv1.setItemText(6, _translate("mw", "100mV", None))
        self.oscilloVdiv1.setItemText(7, _translate("mw", "200mV", None))
        self.oscilloVdiv1.setItemText(8, _translate("mw", "500mV", None))
        self.oscilloVdiv1.setItemText(9, _translate("mw", "1V", None))
        self.oscilloVdiv1.setItemText(10, _translate("mw", "2V", None))
        self.oscilloVdiv1.setItemText(11, _translate("mw", "5V", None))
        self.oscilloVdiv1.setItemText(12, _translate("mw", "10V", None))
        self.oscilloVdiv1.setItemText(13, _translate("mw", "20V", None))
        self.oscilloSet.setText(_translate("mw", "Set", None))
        self.label_9.setText(_translate("mw", "t/div", None))
        self.oscilloTdiv.setItemText(0, _translate("mw", "100 ns", None))
        self.oscilloTdiv.setItemText(1, _translate("mw", "200 ns", None))
        self.oscilloTdiv.setItemText(2, _translate("mw", "500 ns", None))
        self.oscilloTdiv.setItemText(3, _translate("mw", "1 mks", None))
        self.oscilloTdiv.setItemText(4, _translate("mw", "2 mks", None))
        self.oscilloTdiv.setItemText(5, _translate("mw", "5 mks", None))
        self.oscilloTdiv.setItemText(6, _translate("mw", "10 mks", None))
        self.oscilloTdiv.setItemText(7, _translate("mw", "20 mks", None))
        self.oscilloTdiv.setItemText(8, _translate("mw", "50 mks", None))
        self.oscilloTdiv.setItemText(9, _translate("mw", "100 mks", None))
        self.oscilloTdiv.setItemText(10, _translate("mw", "200 mks", None))
        self.oscilloTdiv.setItemText(11, _translate("mw", "500 mks", None))
        self.oscilloTdiv.setItemText(12, _translate("mw", "1 ms", None))
        self.oscilloTdiv.setItemText(13, _translate("mw", "2 ms", None))
        self.oscilloTdiv.setItemText(14, _translate("mw", "5 ms", None))
        self.oscilloTdiv.setItemText(15, _translate("mw", "10 ms", None))
        self.oscilloTdiv.setItemText(16, _translate("mw", "20 ms", None))
        self.oscilloTdiv.setItemText(17, _translate("mw", "50 ms", None))
        self.oscilloTdiv.setItemText(18, _translate("mw", "100 ms", None))
        self.oscilloTdiv.setItemText(19, _translate("mw", "200 ms", None))
        self.oscilloTdiv.setItemText(20, _translate("mw", "500 ms", None))
        self.oscilloTdiv.setItemText(21, _translate("mw", "1 s", None))
        self.oscilloTdiv.setItemText(22, _translate("mw", "2 s", None))
        self.oscilloTdiv.setItemText(23, _translate("mw", "5 s", None))
        self.oscilloTdiv.setItemText(24, _translate("mw", "10 s", None))
        self.oscilloTdiv.setItemText(25, _translate("mw", "50 s", None))
        self.oscilloTdiv.setItemText(26, _translate("mw", "100 s", None))
        self.oscilloAuto.setText(_translate("mw", "Auto", None))
        self.CH1Val_std.setText(_translate("mw", "val1_std", None))
        self.oscilloFreq.setText(_translate("mw", "freq", None))
        self.CH1Val.setText(_translate("mw", "nan", None))
        self.CH2Val.setText(_translate("mw", "nan", None))
        self.dataSources.setItemText(self.dataSources.indexOf(self.page_HAMEG), _translate("mw", "HAMEG", None))
        self.CCD_connect.setText(_translate("mw", "Connect", None))
        self.CCD_trigger.setItemText(0, _translate("mw", "Int.", None))
        self.CCD_trigger.setItemText(1, _translate("mw", "Ext.", None))
        self.label_2.setText(_translate("mw", "%", None))
        self.label_5.setText(_translate("mw", "D4Sigma:", None))
        self.D4Sigma.setToolTip(_translate("mw", "fast diameter", None))
        self.D4Sigma.setText(_translate("mw", "nan", None))
        self.label_6.setText(_translate("mw", "Integr.:", None))
        self.CCD_sum.setText(_translate("mw", "nan", None))
        self.dataSources.setItemText(self.dataSources.indexOf(self.page_CCD), _translate("mw", "CCD", None))
        self.setStepperSpeed.setText(_translate("mw", "setSpeed", None))
        self.CWMoveToStop.setText(_translate("mw", "|||<<<", None))
        self.openAngleSensorPort.setText(_translate("mw", "Open", None))
        self.currentAngle.setText(_translate("mw", "ang", None))
        self.CWHome.setText(_translate("mw", "<<Home", None))
        self.CCWMoveToStop.setText(_translate("mw", ">>>||", None))
        self.CCWHome.setText(_translate("mw", "Home>>", None))
        self.stepperStop.setText(_translate("mw", "STOP", None))
        self.stepperLock.setText(_translate("mw", "lock", None))
        self.setCustomAngle.setText(_translate("mw", "setAngle", None))
        self.moveToAngle.setText(_translate("mw", "moveTo", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.stepper_page), _translate("mw", "Stepper", None))
        self.groupBox_4.setTitle(_translate("mw", "Filters", None))
        self.prevFilter.setText(_translate("mw", "<<", None))
        self.nextFilter.setText(_translate("mw", ">>", None))
        item = self.filtersTab.verticalHeaderItem(0)
        item.setText(_translate("mw", "0", None))
        item = self.filtersTab.verticalHeaderItem(1)
        item.setText(_translate("mw", "1", None))
        item = self.filtersTab.verticalHeaderItem(2)
        item.setText(_translate("mw", "2", None))
        item = self.filtersTab.verticalHeaderItem(3)
        item.setText(_translate("mw", "3", None))
        item = self.filtersTab.verticalHeaderItem(4)
        item.setText(_translate("mw", "4", None))
        item = self.filtersTab.verticalHeaderItem(5)
        item.setText(_translate("mw", "5", None))
        item = self.filtersTab.horizontalHeaderItem(0)
        item.setText(_translate("mw", "name", None))
        item = self.filtersTab.horizontalHeaderItem(1)
        item.setText(_translate("mw", "value", None))
        item = self.filtersTab.horizontalHeaderItem(2)
        item.setText(_translate("mw", "range", None))
        __sortingEnabled = self.filtersTab.isSortingEnabled()
        self.filtersTab.setSortingEnabled(False)
        item = self.filtersTab.item(0, 0)
        item.setText(_translate("mw", "1", None))
        item = self.filtersTab.item(0, 1)
        item.setText(_translate("mw", "1", None))
        item = self.filtersTab.item(0, 2)
        item.setText(_translate("mw", "1", None))
        item = self.filtersTab.item(1, 0)
        item.setText(_translate("mw", "op06", None))
        item = self.filtersTab.item(1, 1)
        item.setText(_translate("mw", "0.251188643150958", None))
        item = self.filtersTab.item(1, 2)
        item.setText(_translate("mw", "1", None))
        item = self.filtersTab.item(2, 0)
        item.setText(_translate("mw", "op09", None))
        item = self.filtersTab.item(2, 1)
        item.setText(_translate("mw", "0.12589254117941673\n"
"", None))
        item = self.filtersTab.item(2, 2)
        item.setText(_translate("mw", "1", None))
        item = self.filtersTab.item(3, 0)
        item.setText(_translate("mw", "op18", None))
        item = self.filtersTab.item(3, 1)
        item.setText(_translate("mw", "0.015848931924611134", None))
        item = self.filtersTab.item(3, 2)
        item.setText(_translate("mw", "1", None))
        item = self.filtersTab.item(4, 0)
        item.setText(_translate("mw", "op09,op18,op18", None))
        item = self.filtersTab.item(4, 1)
        item.setText(_translate("mw", "3.1622776601683795e-05", None))
        item = self.filtersTab.item(4, 2)
        item.setText(_translate("mw", "1", None))
        item = self.filtersTab.item(5, 0)
        item.setText(_translate("mw", "0", None))
        item = self.filtersTab.item(5, 1)
        item.setText(_translate("mw", "1e-22", None))
        item = self.filtersTab.item(5, 2)
        item.setText(_translate("mw", "1", None))
        self.filtersTab.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("mw", "Config", None))
        item = self.globalConfig.verticalHeaderItem(0)
        item.setText(_translate("mw", "Wavelength", None))
        item = self.globalConfig.verticalHeaderItem(1)
        item.setText(_translate("mw", "AngleCalibr", None))
        item = self.globalConfig.verticalHeaderItem(2)
        item.setText(_translate("mw", "Object", None))
        item = self.globalConfig.verticalHeaderItem(3)
        item.setText(_translate("mw", "Distance", None))
        item = self.globalConfig.horizontalHeaderItem(0)
        item.setText(_translate("mw", "value", None))
        item = self.globalConfig.horizontalHeaderItem(1)
        item.setText(_translate("mw", "comments", None))
        __sortingEnabled = self.globalConfig.isSortingEnabled()
        self.globalConfig.setSortingEnabled(False)
        item = self.globalConfig.item(0, 0)
        item.setText(_translate("mw", "1064", None))
        item = self.globalConfig.item(0, 1)
        item.setText(_translate("mw", "nm", None))
        item = self.globalConfig.item(1, 0)
        item.setText(_translate("mw", "0.5", None))
        item = self.globalConfig.item(3, 0)
        item.setText(_translate("mw", "34", None))
        item = self.globalConfig.item(3, 1)
        item.setText(_translate("mw", "cm", None))
        self.globalConfig.setSortingEnabled(__sortingEnabled)
        self.saveConfig.setText(_translate("mw", "save", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Settings), _translate("mw", "FILTERS", None))
        self.SMD_connect.setText(_translate("mw", "connect", None))
        self.groupBox_2.setTitle(_translate("mw", "SM1", None))
        self.label_3.setText(_translate("mw", "Endstops:", None))
        self.SM1_stepsCounter.setToolTip(_translate("mw", "<html><head/><body><p>SM1 driver stepCounter</p></body></html>", None))
        self.SM1_stepsCounter.setText(_translate("mw", "nan", None))
        self.SM1_position.setToolTip(_translate("mw", "<html><head/><body><p>SM1 position</p></body></html>", None))
        self.SM1_position.setText(_translate("mw", "nan", None))
        self.SM1_left2end.setText(_translate("mw", "|<<", None))
        self.SM1_stepLeft.setText(_translate("mw", "<", None))
        self.SM1_stepRight.setText(_translate("mw", ">", None))
        self.SM1_right2end.setText(_translate("mw", ">>|", None))
        self.SM1_tabStep.setText(_translate("mw", "tabStep", None))
        self.SM1_reset.setText(_translate("mw", "reset", None))
        self.SM1_stop.setText(_translate("mw", "stop", None))
        self.SM1_absMove.setText(_translate("mw", "MoveTo", None))
        self.SM1_lock.setText(_translate("mw", "Lock", None))
        self.groupBox_3.setTitle(_translate("mw", "SM2", None))
        self.label_4.setText(_translate("mw", "Endstops:", None))
        self.SM2_lock.setText(_translate("mw", "Lock", None))
        self.SM2_stepsCounter.setText(_translate("mw", "nan", None))
        self.SM2_position.setText(_translate("mw", "nan", None))
        self.SM2_left2end.setText(_translate("mw", "|<<", None))
        self.SM2_stepLeft.setText(_translate("mw", "<", None))
        self.SM2_stepRight.setText(_translate("mw", ">", None))
        self.SM2_right2end.setText(_translate("mw", ">>|", None))
        self.SM2_tabStep.setText(_translate("mw", "tabStep", None))
        self.SM2_reset.setText(_translate("mw", "reset", None))
        self.SM2_absMove.setText(_translate("mw", "MoveTo", None))
        self.SM2_stop.setText(_translate("mw", "stop", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.SMD), _translate("mw", "SMD", None))
        self.menuFIle.setTitle(_translate("mw", "&FIle", None))
        self.menuPlot.setTitle(_translate("mw", "P&lot", None))
        self.actionClose.setText(_translate("mw", "&Close", None))
        self.actionClean.setText(_translate("mw", "&Clean", None))

